### ISSUE TITLE
swagger-maven-plugin not including schema for POST/PUT in case of successfull response in case of Primitive datatype response

### ISSUE THREAD

**Issue by huded** [kongchen/swagger-maven-plugin#223]
Hi,
I am currently using swagger-maven-plugin version 3.1.1-SNAPSHOT and swagger core 1.5.3 .
I am using spring MVC controllers to generate REST API's.

In case of success response,one of the method in controller is returning "String" and another method returning "HashMap<String,String>".Even its been Swagger annotated.But the generated swagger.json and generated html not showing up the schema in case of successful POST/PUT

Controller piece:

1)

 @ApiOperation(value="Create Account", 
        notes="This method will validate the information passed before attempting to create a new Account. It will check if the " +
            "accountId, account Name, creation date information is correct. Thereafter, the account creation process starts ",
        response=String.class,
        consumes="application/json, application/xml",
        produces="application/json, application/xml"
        )
    @ApiResponses(value = { 
    	    @ApiResponse(code = 200, message = "Successful response",response=String.class),
    	    @ApiResponse(code = 420, message = "Acccount cannot be created",response=RestErrorMessage.class),
    	    @ApiResponse(code = 500, message = "Unkown error",response=RestErrorMessage.class) })
    @RequestMapping(value = "/accounts/{accountId}", method = RequestMethod.PUT)
    public ResponseEntity<?> createAccount( @ApiParam(value="This parameter provides account Id for the new account.") @PathVariable("accountId") Integer accountId,@ApiParam(value="This parameter encapsulates new account information.")@RequestBody Account acct) {

2)

	@ApiOperation(value="Encrypt String",
			response=HashMap.class,
			produces="application/json,application/xml")
	 @ApiResponses(value = { 
	    	    @ApiResponse(code = 200, message = "Successful response",response=HashMap.class),
	    	    @ApiResponse(code = 300, message = "Encryption failed",response=FRestErrorMessage.class),
	    	    @ApiResponse(code = 500, message = "Unkown error",response=RestErrorMessage.class) })
	@RequestMapping(value = "/encryptionrequest/encrypt/string/{value}", method = RequestMethod.GET, produces = "application/json")
    public ResponseEntity<?> getEncryptedValue(@ApiParam(value="This parameter provides the text that needs to be encrypted.")@PathVariable("value") String value)

Generated JSON:
1)
 "put" : {
        "summary" : "Create Account",
        "description" : "This method will validate the information passed before attempting to create a new Account. It will check if the accountId, account Name, creation date information is correct. Thereafter, the account creation process starts ",
        "operationId" : "createAccount",
        "parameters" : [ {
          "name" : "accountId",
          "in" : "path",
          "description" : "This parameter provides account Id for the new account.",
          "required" : true,
          "type" : "integer",
          "format" : "int32"
        }, {
          "in" : "body",
          "name" : "body",
          "description" : "This parameter encapsulates new account information.",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Account"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful response"
          },

2)
 "get" : {
        "summary" : "Encrypt String",
        "description" : "",
        "operationId" : "getEncryptedValue",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "value",
          "in" : "path",
          "description" : "This parameter provides the text that needs to be encrypted.",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful response"
          },

HTML snapshots:
1)
![issue1](https://cloud.githubusercontent.com/assets/14162711/9717538/34ef160c-5591-11e5-93dc-531f26d39307.png)

2)
![issue2](https://cloud.githubusercontent.com/assets/14162711/9717541/3af2762a-5591-11e5-8a20-a228d9e3c39e.png)

**Comment by who** [comment]
@huded 

This has been fixed in the latest version.  Please use swagger-maven-plugin 3.1.2.

**Comment by pickywawa** [comment]
Hello. 
I'm using swagger-maven-plugin 3.1.7 and swagger 1.5.17. When I generate, schema is still not included for primitives types.

My sources :

`@POST
	@Path("/prepareLogin")
	@ApiOperation(value = "Prepares CPS authentication")
	@SecuredLogin
	@ApiResponses(value = {
			@ApiResponse(code = HttpURLConnection.HTTP_OK, message = "Prepare login response", response = String.class),
			@ApiResponse(code = HttpURLConnection.HTTP_INTERNAL_ERROR, message = "Internal error", response = ProxyErrorsResponse.class),
			@ApiResponse(code = HttpURLConnection.HTTP_UNAUTHORIZED, message = "Authentication error", response = ProxyErrorsResponse.class)})
	public Response prepareLogin()
											throws ValidationException {
		String response = this.gConnexion.prepareLogin();
		return Response.ok().entity(response).build();
	}`

Generate file : 

```
"/connexion/prepareLogin" : {
      "post" : {
        "tags" : [ "Connexion" ],
        "summary" : "Prepares CPS authentication",
        "description" : "",
        "operationId" : "prepareLogin",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "idApplication",
          "in" : "header",
          "required" : false,
          "type" : "string",
          "default" : ""
        }, {
          "name" : "idApplicationProfile",
          "in" : "header",
          "required" : false,
          "type" : "string",
          "default" : ""
        } ],
        "responses" : {
          "200" : {
            "description" : "Prepare login response"
          },
          "401" : {
            "description" : "Authentication error",
            "schema" : {
              "$ref" : "#/definitions/ProxyErrorsResponse"
            }
          },
          "500" : {
            "description" : "Internal error",
            "schema" : {
              "$ref" : "#/definitions/ProxyErrorsResponse"
            }
          }
        }
      }
    }

```


Have you an idea?

Thanks 
Alexis
