### ISSUE TITLE
@RequestHeader not recognized without an @ApiParam annotation

### ISSUE THREAD

**Issue by ozcarioca** [kongchen/swagger-maven-plugin#234]
@RequestHeader is not listed as a valid annotation in AbstractReader.hasValidAnnotations(List<Annotation> parameterAnnotations)
but is fully implemented in SpringSwaggerExtension.extractParameterFromAnnotation. 

If the method has only the @RequestHeader as a parameter the plugin does not pick it up automatically.

@ApiOperation("")
@RequestMapping(value = "/payments/{creditCard}", method = RequestMethod.GET)
public String processCreditCard(@RequestHeader(value="param-creditcard") String creditCard) {
        return "Credit Card Number: " + creditCard;
}

Only works if @ApiParam is added.

@ApiOperation("")
@RequestMapping(value = "/payments/{creditCard}", method = RequestMethod.GET)
public String processCreditCard(@ApiParam() @RequestHeader(value="param-creditcard") String creditCard) {
        return "Credit Card Number: " + creditCard;
}

**Comment by who** [comment]
Thanks for filing this - I've fixed it in this commit: https://github.com/kongchen/swagger-maven-plugin/commit/2b3eeaf941856b84d68bf7eb4c7d34680b08acfa

**Comment by Nthalk** [comment]
This is still an issue with JAX-RS, because the parameter might not have ANY annotations.

I believe for JAX-RS, you take the first parameter that is not annotated with `*Param`, or is a JAX-RS injectable class, and then THAT is the body param in a `POST` method.

**Comment by who** [comment]
@Nthalk The solution for JAX-RS body params is to add an `@ApiParam()` annotation to it.
