### ISSUE TITLE
Generated Swagger is invalid when a path parameter regex contains a slash ('/')

### ISSUE THREAD

**Issue by bryonjacob** [kongchen/swagger-maven-plugin#304]
When an annotated path uses a regex that includes a `/` character, the resulting swagger definition is generated wrongly.

I forked the `swagger-maven-example` and made a small change that demonstrates this behavior:
https://github.com/bryonjacob/swagger-maven-example/compare/66360d6...demonstrate-regex-issue

```
41   41      @GET
42        -  @Path("/{petId}")
     42   +  @Path("/{petId : [^/]*}")
43   43      @ApiOperation(value = "Find pet by ID", 
44   44        notes = "Returns a pet when ID < 10.  ID > 10 or nonintegers will simulate API error conditions", 
45   45        response = Pet.class,
```

resulting in swagger.json that looks like:

```
...
    "/pet/{petId}/]*}" : {
      "get" : {
        "tags" : [ "pet" ],
...
```

I'm assuming that this is because the swagger generator is splitting the path first on `/`s and then parsing inside each segment, rather than finding all the `{...}` delimited params and handling those?  That's just a guess based on the symptom, haven't dug into the plugin code yet.

**Comment by bryonjacob** [comment]
Appears that this is due to https://github.com/swagger-api/swagger-core/issues/1433

**Comment by bryonjacob** [comment]
I'm perplexed, this issue has been reported against `swagger-core`, and seemingly fixed.  This unit test:
https://github.com/swagger-api/swagger-core/blob/v1.5.4/modules/swagger-core/src/test/java/io/swagger/PathUtilsTest.java#L14-L20

covers the phenomenon I'm seeing.  That's in the `v1.5.4` tag, which should correspond to the code that the plugin is using (I'm seeing this behavior in version `3.1.2` of the `swagger-maven-plugin`):
https://github.com/kongchen/swagger-maven-plugin/blob/swagger-maven-plugin-3.1.2/pom.xml#L54

I'll keep digging - this must not be the code path being executed...

**Comment by haywhisksoftware** [comment]
As you noted, this issue has been fixed in swagger-core.

However, swagger-maven-plugin re-parses the output of Swagger using code from circa `v1.5.0` of swagger-jaxrs -- check out AbstractReader.java

I've got a patch almost ready, but I'm having problems with the yaml test cases.

**Comment by peterberkman** [comment]
this is still an issue with both swagger core and Angular swagger-ui:

<pre>
@Path("/set/{id : (/id)?}")
</pre>
